version: 2
registries:
  npm-registry-npm-fontawesome-com:
    type: npm-registry
    url: https://npm.fontawesome.com
    token: "${{secrets.NPM_REGISTRY_NPM_FONTAWESOME_COM_TOKEN}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "02:00"
    timezone: America/Chicago
  open-pull-requests-limit: 3
  ignore:
  - dependency-name: next
    versions:
    - 10.0.7
    - 10.0.8
    - 10.0.9
    - 10.1.1
    - 10.1.2
    - 10.1.3
  - dependency-name: date-fns
    versions:
    - 2.18.0
    - 2.20.0
    - 2.20.1
    - 2.20.2
    - 2.20.3
    - 2.21.0
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: styled-components
    versions:
    - 5.2.2
  - dependency-name: react-select
    versions:
    - 4.2.0
    - 4.2.1
  registries:
  - npm-registry-npm-fontawesome-com
