name: Graveyard
on:
  pull_request:
    branches: [ main ]
    paths:
      - 'graveyard.json'
      - 'graveyard.test.ts'
      - 'package.json'
jobs: 
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 'lts/*'
      - name: Install pnpm
        run: npm install -g pnpm@9
      - name: Install dependencies
        run: pnpm install
      - name: Run Tests
        run: pnpm run test
