name: Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Install Yarn
        run: npm install yarn
      - name: Install dependencies
        run: yarn
      - name: Run Build
        run: yarn run build
      - name: Check Types
        run: yarn run tsc
      - name: Run Tests
        run: yarn run test
